### ISSUE TITLE
Wait for multiple styles of font to load?

### ISSUE THREAD

**Issue by jhuckaby** [dwighthouse/onfontready#8]
Hello, and I apologize if this question is answered somewhere in the docs, but I read everything and couldn't find an answer.  If I load two different styles or weights of the same font family, i.e. regular and bold like this:

```html
<link href="https://fonts.googleapis.com/css?family=Comfortaa:400,700" rel="stylesheet">
```

Will onFontReady wait for **both** of these variants to load?  I ask because each of which requires its own separate URL and network request.  Meaning, would this code work correctly when both regular and bold are loaded:

```js
onfontready('Comfortaa', function() {
    document.documentElement.className += " fontLoaded";
}
```

Or do I have to do something special in this case?

Thanks!

**Comment by dwighthouse** [comment]
I don't think I call it out in the docs, but if I remember correctly, it wasn't possible to detect this case except by massively increasing the complexity of the library.

I recommend not relying on Google Fonts directly for this scenario, and instead downloading the different font variants you want, and serve them as separate, differently-named fonts. That is, you would create two new font-families "Comfortaa400" and "Comfortaa700", using `@font-face` rules as normal.

Then, you can use the [Multi-Font Detection Techniques](https://github.com/dwighthouse/onfontready/blob/master/docs/multiFontDetection.md) to wait for both.

If you really wanted to define the font variants under a single name, you could probably rig up a simple system where it waited for both fonts to load separately, detecting them, and then switching to a new `@font-face` representation that reference the original URLs, which have already been cached.

Sorry it's complicated. I'm pretty sure I tried to implement this, and was not able to predictably detect that the font was ready, since it would trigger the ready state after either the 400 or 700 weight variation occurred, but not both. It gets further complicated because Google Fonts serves the fonts as multiple files for the different language character sets, not just weights.

onfontready more or less expects one font file/`@font-face` per detection.

**Comment by jhuckaby** [comment]
Ah, I see, thank you for the quick reply and explanation.  It is much appreciated!
